# Generated by Django 5.2.5 on 2025-11-01 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_especialidad', to='centroMedico.especialidad'),
        ),
    ]
