# Generated by Django 5.2.5 on 2025-11-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedico', '0002_alter_cita_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
