# Generated by Django 5.2.5 on 2025-11-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedico', '0003_alter_medico_rut_alter_paciente_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['-especialidad']},
        ),
        migrations.AlterField(
            model_name='medico',
            name='correo',
            field=models.EmailField(error_messages={'unique': 'El correo ya está asociado a un médico en el sistema.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rut',
            field=models.CharField(error_messages={'unique': 'El RUT ya está asociado a un médico en el sistema.'}, max_length=10, unique=True),
        ),
    ]
